# services/voice_profiles/base.py
from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Dict, Optional, Protocol

class LiveAssistant(Protocol):
    instructions: str
    def schema(self) -> str: ...
    def prompt(self, _: str = "", **payload: Any) -> str: ...
    def extract_first_json_object(self, text: str) -> Any: ...

class FinalizeAssistant(Protocol):
    instructions: str
    def prompt(self, _: str = "", **payload: Any) -> str: ...
    def extract_first_json_object(self, text: str) -> Any: ...

@dataclass(frozen=True)
class VoiceLiveProfile:
    id: str
    name: str
    def empty_state(self) -> Dict[str, Any]: ...
    def assistant(self) -> LiveAssistant: ...
    def render(self, state: Dict[str, Any], *, transcript: Optional[str] = None) -> str: ...
    def finalizer(self) -> Optional[FinalizeAssistant]: ...
